# Generated by Django 5.2.5 on 2025-09-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_together', '0004_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='github',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='myuser',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='myuser',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='myuser',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='x_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
