# Generated by Django 5.2.5 on 2025-09-11 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_together', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='accepted_answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for', to='ask_together.answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
