# Generated by Django 5.2.5 on 2025-11-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_together', '0009_question_accepted_answer_question_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
