# Generated by Django 5.2.5 on 2025-12-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_together', '0010_myuser_is_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='downvotes',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='upvotes',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='downvotes',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='upvotes',
            field=models.SmallIntegerField(default=0),
        ),
    ]
