# Generated by Django 5.2.5 on 2025-12-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_together', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='upvotes',
            field=models.SmallIntegerField(default=0),
        ),
    ]
