# Generated by Django 5.2.5 on 2026-01-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_together', '0013_notification_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
