# Generated by Django 5.2.5 on 2026-01-30 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_together', '0014_savedquestion'),
        ('ask_together', '0015_question_search_vector_and_more'),
    ]

    operations = [
    ]
